name: libraryFullStack
version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: biblioteca-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bibliotecadb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
